### ISSUE TITLE
Message > The layout of text message doesn't display well

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#106]
# Actual Result
The new layout makes more spaces between words in a line.
![image](https://user-images.githubusercontent.com/69950655/102482044-33e6ca80-4095-11eb-92a5-865df4f8cd4f.png)

# Expected Result
Please fix the issue, it looks weird. 
The link should be able to continue display in the same line with the short text.

# Environment
Android devices

**Comment by tlle14** [comment]
Thank @bobs4462 
There's no more abnormal space between texts. 
But the link should go after the text instead of displaying in the next line.

**Comment by RockinPaul** [comment]
Flutter team is still working on wrapping issue solutions for text widgets: https://github.com/flutter/flutter/issues/25287
The suggested workaround does not fit Twacode system. However, since the Twake team decided to get rid of Twacode and use Markdown, we'll return to this issue during the new layout system implementation.
