### ISSUE TITLE
The app isn't full-screen displaying

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#111]
# Actual Result
iOS devices display the app like this:
![image](https://user-images.githubusercontent.com/69950655/102574304-06e0f900-4123-11eb-9f57-d5f2d9df8087.png)

Android displays the app:
![image](https://user-images.githubusercontent.com/69950655/102574556-9f777900-4123-11eb-81ef-25abafc0eae0.png)

# Expected Result
The app should display fullscreen, responsive to the device screen

# Environment
Mobile devices

**Comment by tlle14** [comment]
Hi @romanesko  @bobs4462 
Could you please fix the login screen also. 
The other screens seem perfect on iOS.

**Comment by tlle14** [comment]
@bobs4462 I hope this issue will be fixed on Android. The grey top should be white 
![image](https://user-images.githubusercontent.com/69950655/103115270-88410a00-4694-11eb-94e7-0ace950fcb50.png)

**Comment by tlle14** [comment]
Hi @RockinPaul @bobs4462 
Is the fix ready to be tested on this version twake.2.1.0? 
I don't see the change for the Android device.
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/90ede3f2-f27f-4899-a82e-7fcfa52c366e)

**Comment by RockinPaul** [comment]
@tlle14  Right now there are no well-known solutions that work properly on Android.
https://medium.com/dev-genius/different-ways-to-change-the-status-bar-and-navigation-bar-color-ios-and-android-in-flutter-a786e098f573 - for example, none of these will work as expected on Android because:
1) AppBar settings override SystemChrome behavior on the first widget's rebuild after applying setSystemUIOverlayStyle.
2) Android system preferences prevent modifying the status bar color in some versions of this OS.

The only possible way we could try to manage it - is to replace AppBar with a custom solution, which could require a lot of work. Since now we are waiting for the new design to be done and approved, it may lead to redundant efforts.
If we still considering the critical character of this issue, it would be better to create a new one, because it related to the status bar color and not to full-screen appearance (Safe Area management).

**Comment by tlle14** [comment]
I see. 
Thank @RockinPaul for the detailed explanation. 
I should close this ticket and wait for the user feedback.
