### ISSUE TITLE
Messages doesn't appear right after sending

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#189]
# Actual Result
The message doesn't display instantly on the screen after submit

https://user-images.githubusercontent.com/69950655/105024128-5007ce00-5a7e-11eb-8f9a-d947d2d1bf82.mp4

# Expected Result
The message should display right after submitted

# Environment
Android app
Build version: twake.2.1.0

**Comment by bobs4462** [comment]
The issue is twacode, currently the application does not support parsing the message into twacode structure, so we send the message first, and then wait for the server to parse it for us.

In order to solve the issue we need to implement twacode parser in app. 

@RomaricMourgues when approximately are you planning to work on twacode? You mentioned once, that you are planning to simplify it

**Comment by RomaricMourgues** [comment]
We plan to work on it Q2-Q3 2021.
Twacode will evolve into extended markdown parsing, the source of truth will be a string (and not an array like now).
So you can get the text part of the messages when available and just parse it as pure markdown maybe ?

**Comment by tlle14** [comment]
Thank @bobs4462 and @RomaricMourgues 
Retest pass
https://images.zenhubusercontent.com/309637937/c5448f4a-0ec9-4e8e-9b3e-4bad0118515b/videoadf62947_6ac9_404c_87f5_ea1e6c192b57video.mp4
