### ISSUE TITLE
Create a direct chat is not convenient for user 

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#191]
# Actual Result
Recently, creating a direct chat is the same way as creating a channel, which is not convenient for users to find a person he wants to chat with. And the UI is not appropriate.
This feature is not working now.

# Expected Result
Need help from BA, Designer to finish this feature. 

# Environment
Android mobile
Build version: twake.2.1.0

**Comment by BastiaanVanGaalen** [comment]
@tlle14 Creating direct conversation must be done with one tap on the screen. Let's figure out what's is wrong about current flow.

**Comment by tlle14** [comment]
Hi @BastiaanVanGaalen @RockinPaul @bobs4462 
The feature isn't working. 
1. When selecting the search box, the keyboard doesn't show. 

https://images.zenhubusercontent.com/309637937/bd4baceb-1588-4e40-bd49-2126aa1f0746/video1b616031_1009_49e9_ac06_99edbc35bd94video.mp4

2. We should remove the suggested member, it's not appropriate. 
The member list is not correct data. 
Even it's real data, when we have a hundred people, it will affect the screen loading speed.
=> We should keep the screen simple.
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/4650430f-473
e-4de8-9813-d33e367e1a3b)

**Comment by tlle14** [comment]
Default displaying is simplified
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/90ad0fd8-50fa-4f69-9f27-cfbc0d76890c)

But the function is not working. 
I will keep update in another issue. 
Thank @BastiaanVanGaalen @RockinPaul

**Comment by BastiaanVanGaalen** [comment]
@tlle14 Can we verify whether or not the data (list of all members) is real? If it's real we would rather display members because of several considerations;
- performance issues are manageable (we will be using kind of a lazy load in which member cells load up with scrolling. The list will be sorted by alphabetically
- Why to display all members? Imagine i need to find a member but i have no idea how his or her name is spelled correctly (Vietnamese or French full name).

**Comment by tlle14** [comment]
Hi @BastiaanVanGaalen 
I've checked the Console page, the data is not real. 

About displaying the member list, please discuss with your PO for the final result. I just suggest using the solution as on the Web version.
