### ISSUE TITLE
Channel > Date-time is displaying in the incorrect format

### ISSUE THREAD

**Issue by tlle14** [TwakeApp/Mobile#60]
# Actual Result
The date-time is too long and display in the incorrect format.
Example: 10:05 -> 10:5
![image](https://user-images.githubusercontent.com/69950655/101311327-bc8a8d00-3883-11eb-8d22-e663f1962f08.png)

# Expected Result
Date and time should be displayed in the correct format and shortly.

# Environment
All mobile devices

**Comment by bobs4462** [comment]
Changed the format to shorter one in threads, but it displays short version only if the current year is the same as message's creation year, otherwise it will display the year too, making it longer. It's required because we need to distinguish the old messages' timestamp somehow. If you have better ideas regarding datatime format, I'm open to suggestions.

**Comment by tlle14** [comment]
Or we should decrease the username's font size. How do you think? @bobs4462

**Comment by bobs4462** [comment]
Yes, I'll experiment with username fontsize
